## This configuration was generated by terraform-provider-oci

resource oci_osmanagement_managed_instance export_oke-caojrtmpvka-njgvsueanpa-sa7i7gwheua-1_2 {
  is_data_collection_authorized = "false"
  managed_instance_id           = "<placeholder for missing required attribute>" #Required attribute not found in discovery, placeholder value set to avoid plan failure
  #notification_topic_id = <<Optional value not found in discovery>>

  # Required attributes that were not found in discovery have been added to lifecycle ignore_changes
  # This is done to avoid terraform plan failure for the existing infrastructure
  lifecycle {
    ignore_changes = [managed_instance_id]
  }
}

resource oci_osmanagement_managed_instance export_oke-cjlzjbep6iq-nhlqdxxbsiq-soe26proybq-1_2 {
  is_data_collection_authorized = "false"
  managed_instance_id           = "<placeholder for missing required attribute>" #Required attribute not found in discovery, placeholder value set to avoid plan failure
  #notification_topic_id = <<Optional value not found in discovery>>

  # Required attributes that were not found in discovery have been added to lifecycle ignore_changes
  # This is done to avoid terraform plan failure for the existing infrastructure
  lifecycle {
    ignore_changes = [managed_instance_id]
  }
}

resource oci_osmanagement_managed_instance export_oke-caojrtmpvka-njgvsueanpa-sa7i7gwheua-0_2 {
  is_data_collection_authorized = "false"
  managed_instance_id           = "<placeholder for missing required attribute>" #Required attribute not found in discovery, placeholder value set to avoid plan failure
  #notification_topic_id = <<Optional value not found in discovery>>

  # Required attributes that were not found in discovery have been added to lifecycle ignore_changes
  # This is done to avoid terraform plan failure for the existing infrastructure
  lifecycle {
    ignore_changes = [managed_instance_id]
  }
}

resource oci_osmanagement_managed_instance export_oke-cjlzjbep6iq-nhlqdxxbsiq-soe26proybq-2_2 {
  is_data_collection_authorized = "false"
  managed_instance_id           = "<placeholder for missing required attribute>" #Required attribute not found in discovery, placeholder value set to avoid plan failure
  #notification_topic_id = <<Optional value not found in discovery>>

  # Required attributes that were not found in discovery have been added to lifecycle ignore_changes
  # This is done to avoid terraform plan failure for the existing infrastructure
  lifecycle {
    ignore_changes = [managed_instance_id]
  }
}

resource oci_osmanagement_managed_instance export_oke-caojrtmpvka-njgvsueanpa-sa7i7gwheua-2_2 {
  is_data_collection_authorized = "false"
  managed_instance_id           = "<placeholder for missing required attribute>" #Required attribute not found in discovery, placeholder value set to avoid plan failure
  #notification_topic_id = <<Optional value not found in discovery>>

  # Required attributes that were not found in discovery have been added to lifecycle ignore_changes
  # This is done to avoid terraform plan failure for the existing infrastructure
  lifecycle {
    ignore_changes = [managed_instance_id]
  }
}

resource oci_osmanagement_managed_instance export_oke-cjlzjbep6iq-nhlqdxxbsiq-soe26proybq-0_2 {
  is_data_collection_authorized = "false"
  managed_instance_id           = "<placeholder for missing required attribute>" #Required attribute not found in discovery, placeholder value set to avoid plan failure
  #notification_topic_id = <<Optional value not found in discovery>>

  # Required attributes that were not found in discovery have been added to lifecycle ignore_changes
  # This is done to avoid terraform plan failure for the existing infrastructure
  lifecycle {
    ignore_changes = [managed_instance_id]
  }
}

