# Copyright (c) 2021, Oracle and/or its affiliates. All rights reserved.
# Licensed under the Universal Permissive License v 1.0 as shown at https://oss.oracle.com/licenses/upl.

title: "MLOps Resources Deployment"
Description: "Terraform Script to deploy MLOps resourvces to OCI"
schemaVersion: 1.1.0
version: "20211112"
locale: "en"

variableGroups:
- title: General Configuration
  visible: false
  variables:
    - compartment_ocid
    - tenancy_ocid
    - region

# - title: Required Configuration
#   visible: true
#   variables:
#     - awx_cluster_name
#     - resource_naming_prefix

# - title: Optional Configuration
#   visible: true
#   variables:
#     - awx_node_ssh_public_key
#     - image_operating_system
#     - image_operating_system_version
#     - instance_shape
#     - shape_ocpus
#     - shape_mems
#     - awx_execution_env_image_name

variables:
  compartment_ocid:
    type: oci:identity:compartment:id
    required: true
    title: "Compartment OCID" 
    description: "Please select the target compartment"

  tenancy_ocid:
    type: oci:identity:tenancy:id
    required: true
    title: "Tenancy OCID"
    description: "Please select the target tenancy"

  region:
    type: oci:identity:region:name
    required: true
    title: "Region"
    description: "Please select the target region"

# outputs:
#   cluster:
#     type: string
#     title: "OKE cluster details"
#     visible: true

#   flex_node_pool:
#     type: string
#     title: "OKE node pool details"
#     visible: true

#   awx_login_password:
#     type: string
#     title: "AWX login Password"
#     displayText: "AWX UI login password"
#     visible: true

#   awx_ui_ip:
#     type: string
#     title: "AWX UI IP address"
#     displayText: "AWX UI IP address"
#     visible: true