# Copyright (c) 2021, Oracle and/or its affiliates. All rights reserved.
# Licensed under the Universal Permissive License v 1.0 as shown at https://oss.oracle.com/licenses/upl.

title: "MLOps Resources Deployment"
Description: "Terraform Script to deploy MLOps resourvces to OCI"
schemaVersion: 1.1.0
version: "20211112"
locale: "en"

variableGroups:
- title: General Configuration
  visible: false
  variables:
    - compartment_ocid
    - tenancy_ocid
    - region

- title: Required Configuration
  visible: true
  variables:
    - awx_cluster_name
    - resource_naming_prefix

- title: Optional Configuration
  visible: true
  variables:
    - awx_node_ssh_public_key
    - image_operating_system
    - image_operating_system_version
    - instance_shape
    - shape_ocpus
    - shape_mems
    - awx_execution_env_image_name

variables:
  compartment_ocid:
    type: oci:identity:compartment:id
    required: true
    title: ${Messages.solutionsHub.genericVariables.compartment.title()}
    description: ${Messages.solutionsHub.genericVariables.compartment.description()}

  tenancy_ocid:
    type: oci:identity:tenancy:id
    required: true
    title: ${Messages.solutionsHub.genericVariables.tenancy.title()}
    description: ${Messages.solutionsHub.genericVariables.tenancy.description()}

  region:
    type: oci:identity:region:name
    required: true
    title: ${Messages.solutionsHub.genericVariables.region.title()}
    description: ${Messages.solutionsHub.genericVariables.region.description()}

  resource_naming_prefix:
    type: string
    required: true
    title: ${Messages.solutionsHub.solutions.ociAnsibleAWX.variables.resource_naming_prefix.title()}
    description: ${Messages.solutionsHub.solutions.ociAnsibleAWX.variables.resource_naming_prefix.description()}
    minLength: 2
    maxLength: 5

  awx_cluster_name:
    type: string
    required: true
    title: ${Messages.solutionsHub.solutions.ociAnsibleAWX.variables.awx_cluster_name.title()}
    description: ${Messages.solutionsHub.solutions.ociAnsibleAWX.variables.awx_cluster_name.description()}
    minLength: 3
    maxLength: 15

  image_operating_system:
    type: string
    required: false
    title: ${Messages.solutionsHub.solutions.ociAnsibleAWX.variables.image_operating_system.title()}
    description: ${Messages.solutionsHub.solutions.ociAnsibleAWX.variables.image_operating_system.description()}
    default: "Oracle Linux"

  image_operating_system_version:
    type: string
    required: false
    title: ${Messages.solutionsHub.solutions.ociAnsibleAWX.variables.image_operating_system_version.title()}
    description: ${Messages.solutionsHub.solutions.ociAnsibleAWX.variables.image_operating_system_version.description()}
    default: "7.9"

  instance_shape:
    type: string
    required: false
    title: ${Messages.solutionsHub.solutions.ociAnsibleAWX.variables.instance_shape.title()}
    description: ${Messages.solutionsHub.solutions.ociAnsibleAWX.variables.instance_shape.description()}
    default: "VM.Standard.E3.Flex"

  shape_ocpus:
    type: integer
    required: false
    title: ${Messages.solutionsHub.solutions.ociAnsibleAWX.variables.shape_ocpus.title()}
    description: ${Messages.solutionsHub.solutions.ociAnsibleAWX.variables.shape_ocpus.description()}
    default: 8
    minimum: 6

  shape_mems:
    type: integer
    required: false
    title: ${Messages.solutionsHub.solutions.ociAnsibleAWX.variables.shape_mems.title()}
    description: ${Messages.solutionsHub.solutions.ociAnsibleAWX.variables.shape_mems.description()}
    minimum: 8

  awx_execution_env_image_name:
    type: string
    required: false
    title: ${Messages.solutionsHub.solutions.ociAnsibleAWX.variables.awx_execution_env_image_name.title()}
    description: ${Messages.solutionsHub.solutions.ociAnsibleAWX.variables.awx_execution_env_image_name.description()}

  awx_node_ssh_public_key:
    type: string
    required: false
    title: ${Messages.solutionsHub.solutions.ociAnsibleAWX.variables.awx_node_ssh_public_key.title()}
    description: ${Messages.solutionsHub.solutions.ociAnsibleAWX.variables.awx_node_ssh_public_key.description()}
    default: ""

outputs:
  cluster:
    type: string
    title: "OKE cluster details"
    visible: true

  flex_node_pool:
    type: string
    title: "OKE node pool details"
    visible: true

  awx_login_password:
    type: string
    title: "AWX login Password"
    displayText: "AWX UI login password"
    visible: true

  awx_ui_ip:
    type: string
    title: "AWX UI IP address"
    displayText: "AWX UI IP address"
    visible: true