# Copyright (c) 2021, Oracle and/or its affiliates. All rights reserved.
# Licensed under the Universal Permissive License v 1.0 as shown at https://oss.oracle.com/licenses/upl.

title: "MLOps Resources Deployment"
Description: "Terraform Script to deploy MLOps resourvces to OCI"
schemaVersion: 1.1.0
version: "20211112"
locale: "en"

variableGroups:
- title: General Configuration
  visible: false
  variables:
    - compartment_ocid
    - tenancy_ocid
    - region

- title: Required Configuration
  visible: true
  variables:
    - resource_naming_prefix

- title: Network Configuration
  visible: true
  variables:
    - generic_vcn_cidr_blocks
    - oke_vcn_cidr_blocks

- title: OKE Cluster Configuration
  visible: true
    # - image_operating_system
    # - image_operating_system_version
    # - instance_shape
    # - shape_ocpus
    # - shape_mems

variables:
  compartment_ocid:
    type: oci:identity:compartment:id
    required: true
    title: "Compartment OCID" 
    description: "Please select the target compartment"

  tenancy_ocid:
    type: oci:identity:tenancy:id
    required: true
    title: "Tenancy OCID"
    description: "Please select the target tenancy"

  region:
    type: oci:identity:region:name
    required: true
    title: "Region"
    description: "Please select the target region"

  resource_naming_prefix:
    type: string
    required: true
    title: "Resource naming prefix"
    description: "Please input the resource naming prefix for OCI resources"

  generic_vcn_cidr_blocks:
    type: string
    required: true
    title: "Generic VCN CIDR Block"
    description: "Please input the Generic VCN CIDR Block"

  oke_vcn_cidr_blocks:
    type: string
    required: true
    title: "OKE VCN CIDR Block"
    description: "Please input the OKE VCN CIDR Block"

  ssh_public_key:
    title: "SSH Public Key"
    type: oci:core:ssh:publickey
    description: "The public SSH key for the key-pair that you want to use, if you wish to login to the instances over SSH"
    required: true

  ssh_private_key:
    title: "Generated Private Key for SSH Access"
    description: The private SSH key for the key-pair that you want to use
    sensitive: true

# outputs:
#   cluster:
#     type: string
#     title: "OKE cluster details"
#     visible: true

#   flex_node_pool:
#     type: string
#     title: "OKE node pool details"
#     visible: true

#   awx_login_password:
#     type: string
#     title: "AWX login Password"
#     displayText: "AWX UI login password"
#     visible: true

#   awx_ui_ip:
#     type: string
#     title: "AWX UI IP address"
#     displayText: "AWX UI IP address"
#     visible: true