# Copyright (c) 2021, Oracle and/or its affiliates. All rights reserved.
# Licensed under the Universal Permissive License v 1.0 as shown at https://oss.oracle.com/licenses/upl.

title: "MLOps Resources Deployment"
Description: "Terraform Script to deploy MLOps resources to OCI"
informationalText: "Terraform Script to deploy MLOps resources to OCI"
schemaVersion: 1.1.0
version: "20220311"
locale: "en"

variableGroups:
- title: General Configuration
  visible: false
  variables:
    - compartment_ocid
    - tenancy_ocid
    - region

- title: General Configuration
  visible: true
  variables:
    - resource_naming_prefix

- title: Network Configuration
  visible: true
  variables:
    - generic_vcn_cidr_blocks
    - oke_vcn_cidr_blocks
    - oke_k8sapiendpoint_subnet_cidr_block
    - oke_service_lb_subnet_cidr_block
    - oke_nodepool_cidr_block

- title: Functions and Container Registry configuration
  visible: true
  variables:
    - ocir_username
    - ocir_password

variables:
  compartment_ocid:
    type: oci:identity:compartment:id
    required: true
    title: "Compartment OCID" 
    description: "Please select the target compartment"

  tenancy_ocid:
    type: oci:identity:tenancy:id
    required: true
    title: "Tenancy OCID"
    description: "Please select the target tenancy"

  region:
    type: oci:identity:region:name
    required: true
    title: "Region"
    description: "Please select the target region"

  region_key:
    type: oci:identity:region:key
    required: true
    title: Region Key"
    description: "Please select the target region"

  resource_naming_prefix:
    type: string
    required: true
    title: "Resource naming prefix"
    description: "Please input the resource naming prefix for OCI resources"

  generic_vcn_cidr_blocks:
    type: string
    required: true
    title: "Generic VCN CIDR Block"
    description: "Please input the Generic VCN CIDR Block"

  oke_vcn_cidr_blocks:
    type: string
    required: true
    title: "OKE VCN CIDR Block"
    description: "Please input the OKE VCN CIDR Block"

  oke_k8sapiendpoint_subnet_cidr_block:
    type: string
    required: true
    title: "OKE API Endpoint Subnet CIDR Block"
    description: "Please input the OKE API Endpoint Subnet CIDR Block"

  oke_service_lb_subnet_cidr_block:
    type: string
    required: true
    title: "OKE Service Load Balancer Subnet CIDR Block"
    description: "Please input the OKE Service Load Balancer Subnet CIDR Block"

  oke_nodepool_cidr_block:
    type: string
    required: true
    title: "OKE Node Pool Subnet CIDR Block"
    description: "Please input the OKE Node Pool Subnet CIDR Block"

  ocir_username:
    title: "Username for OCIR Login"
    type: "string"
    description: "Federated: <tenancy-namespace>/oracleidentitycloudservice/<username>, IAM User: <tenancy-namespace>/<username>"

  ocir_password:
    title: "Password for OCIR Login"
    type: password
    description: "Key in the auth token of your user"

# outputs:
#   cluster:
#     type: string
#     title: "OKE cluster details"
#     visible: true

#   flex_node_pool:
#     type: string
#     title: "OKE node pool details"
#     visible: true

#   awx_login_password:
#     type: string
#     title: "AWX login Password"
#     displayText: "AWX UI login password"
#     visible: true

#   awx_ui_ip:
#     type: string
#     title: "AWX UI IP address"
#     displayText: "AWX UI IP address"
#     visible: true